source /etc/makepkg.conf

_nlinux_makepkg_options=()
for _nlinux_makepkg_option in "${OPTIONS[@]}"; do
  case "$_nlinux_makepkg_option" in
    debug|!debug) ;;
    *) _nlinux_makepkg_options+=("$_nlinux_makepkg_option") ;;
  esac
done
OPTIONS=("${_nlinux_makepkg_options[@]}" "!debug")
unset _nlinux_makepkg_options _nlinux_makepkg_option
