[colors]
background = "#11112dFF"
text_primary = "#f3edf7FF"
text_muted = "#7c80b4FF"
accent_primary = "#fff59bFF"
accent_secondary = "#a9aefeFF"
warning = "#9bfeceFF"
error = "#fd4663FF"

[appearance]
border_focused = "#fff59bFF"
border_unfocused = "#11112dFF"
scratchpad_border_focused = "#9bfeceFF"
scratchpad_border_unfocused = "#02e577FF"
outer_border_color = "#070722FF"
insert_hint_color = "#9bfece80"
backdrop_color = "#11112dFF"

[overview]
background_tint = "#07072288"
workspace_background = "#070722FF"
